### ISSUE TITLE
Update module catalog for aws internet gateway

### ISSUE THREAD

**Issue by indirakalagara** [cloud-native-toolkit/terraform-aws-vpc-gateways#3]
Not able to crate a BOM for AWS infra, as Internet gateway moudule is not listed in the catalogue. Need to fix the issue to progress further on the BOM creation.

**Comment by indirakalagara** [comment]
@seansund  @triceam  Can you please help with this

**Comment by triceam** [comment]
Done, catalog is rebuilding: https://github.com/cloud-native-toolkit/automation-modules/blob/main/catalog.yaml
